- id: '1615332131496'
  alias: Turn On Sofa And Dinner Table At Half Brightness
  description: ''
  use_blueprint:
    path: double_switch_off_light_off.yaml
    input:
      switch_id: friends_of_hue_switch
      light1: light.sofa_spots
      light2: light.dinner_table_spots
- id: '1615332193843'
  alias: Turn On Sofa And Dinner Table At Full Brightness
  description: ''
  use_blueprint:
    path: double_switch_hold_light_off.yaml
    input:
      switch_id: friends_of_hue_switch
      light1: light.sofa_spots
      light2: light.dinner_table_spots
- id: '1615334598468'
  alias: Dinner Table Spots Turn On At Full Brightness
  description: ''
  use_blueprint:
    path: single_switch_hold_light_off.yaml
    input:
      switch_id: friends_of_hue_switch
      light: light.dinner_table_spots
- id: '1615334613491'
  alias: Dinner Table Spots Turn On At Half Brightness
  description: ''
  use_blueprint:
    path: single_switch_off_light_off.yaml
    input:
      switch_id: friends_of_hue_switch
      light: light.dinner_table_spots
- id: '1615334836432'
  alias: Sofa Spots Turn On At Full Brightness
  description: ''
  use_blueprint:
    path: single_switch2_hold_light_off.yaml
    input:
      switch_id: friends_of_hue_switch
      light: light.sofa_spots
- id: '1615334951164'
  alias: Sofa Spots Turn On At Half Brightness
  description: ''
  use_blueprint:
    path: single_switch2_off_light_off.yaml
    input:
      switch_id: friends_of_hue_switch
      light: light.sofa_spots
- id: '1615479696396'
  alias: Dinner Table Spots On/Off
  description: ''
  use_blueprint:
    path: zigbee_switch/light_on_off.yaml
    input:
      switch_id: friends_of_hue_switch
      light: light.dinner_table_spots
- id: '1615479713980'
  alias: Dinner Table Spots Increase/Decrease
  description: ''
  use_blueprint:
    path: zigbee_switch/light_increase_decrease.yaml
    input:
      switch_id: friends_of_hue_switch
      light: light.dinner_table_spots
- id: '1615479732070'
  alias: Sofa Spots On/Off
  description: ''
  use_blueprint:
    path: zigbee_switch/light2_on_off.yaml
    input:
      switch_id: friends_of_hue_switch
      light: light.sofa_spots
- id: '1615479750422'
  alias: Sofa Spots Increase/Decrease
  description: ''
  use_blueprint:
    path: zigbee_switch/light2_increase_decrease.yaml
    input:
      switch_id: friends_of_hue_switch
      light: light.sofa_spots
- id: '1615480694084'
  alias: Sofa And Dinner Table On/Off
  description: ''
  use_blueprint:
    path: zigbee_switch/double_on_off.yaml
    input:
      switch_id: friends_of_hue_switch
      light: light.sofa_spots
      light2: light.dinner_table_spots
- id: '1615480713754'
  alias: Sofa And Dinner Table Increase/Decrease
  description: ''
  use_blueprint:
    path: zigbee_switch/double_increase_decrease.yaml
    input:
      switch_id: friends_of_hue_switch
      light: light.sofa_spots
      light2: light.dinner_table_spots
- id: '1615483072039'
  alias: Office Desk Lamp On/Off
  description: ''
  use_blueprint:
    path: zigbee_switch/light_on_off.yaml
    input:
      switch_id: office_test_switch
      light: light.grono_lamp_office
- id: '1618335112346'
  alias: Bar Spots Light Handler
  description: ''
  use_blueprint:
    path: zigbee_switch/light_handler.yaml
    input:
      switch_id: bar_spots_switch_new
      light: light.bar_spots
- id: '1618335131586'
  alias: Bedroom Spots Light Handler
  description: ''
  use_blueprint:
    path: zigbee_switch/light_handler.yaml
    input:
      switch_id: bedroom_switch_new
      light: light.bedroom_spots
- id: '1618335149494'
  alias: Entrance Spots Light Handler
  description: ''
  use_blueprint:
    path: zigbee_switch/light_handler.yaml
    input:
      switch_id: entrance_spots_switch_new
      light: light.entrance_spots
- id: '1618335165111'
  alias: Front Door Spots Light Handler
  description: ''
  use_blueprint:
    path: zigbee_switch/light_handler.yaml
    input:
      switch_id: front_door_switch
      light: light.front_door_spots
- id: '1618335182061'
  alias: Kitchen Spots Light Handler
  description: ''
  use_blueprint:
    path: zigbee_switch/light_handler.yaml
    input:
      switch_id: kitchen_switch
      light: light.kitchen_spots
- id: '1618335201105'
  alias: Stairs Spots Bottom Light Handler
  description: ''
  use_blueprint:
    path: zigbee_switch/light_handler.yaml
    input:
      switch_id: stairs_spots_switch_bottom
      light: light.stairs_spots
- id: '1618335219837'
  alias: Stairs Spots Top Light Handler
  description: ''
  use_blueprint:
    path: zigbee_switch/light_handler.yaml
    input:
      switch_id: stairs_spots_switch_top
      light: light.stairs_spots
- id: '1618511236472'
  alias: Bedroom Roller Blind Handler
  description: ''
  use_blueprint:
    path: zigbee_switch/roller_blind_handler.yaml
    input:
      switch_id: bedroom_switch_blind
      cover: cover.bedroom_blind
- id: '1628692575148'
  alias: Livingroom Blind 1 Handler
  description: Roller Blind handler for small window in livingroom
  use_blueprint:
    path: zigbee_switch/roller_blind_handler.yaml
    input:
      switch_id: livingroom_blind_1_switch
      cover: cover.livingroom_blind_1
