title: Ipad

decluttering_templates:
  !include_dir_merge_named ui/decluttering_templates/


background: var(--background-image)
views:
  # - !include ui/ipad-lights.yaml
  - !include ui/ipad-lights-new.yaml
  - !include ui/ipad-music.yaml
