# button_card_templates: !include ui/home_new/button_card_templates.yaml

decluttering_templates:
  !include_dir_merge_named ui/decluttering_templates/

  
title: Home

background: var(--background-image)
views:
  - !include ui/home_new/home.yaml