- alias: Turn On Basement Hall
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: basement_entrance_and_hall
      event: 2002
  action:
    service: light.turn_on
    entity_id: light.basement_hall_spots

- alias: Turn Off Basement Hall
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: basement_entrance_and_hall
      event: 3002
  action:
    service: light.turn_off
    entity_id: light.basement_hall_spots

- alias: Increase Start Basement Hall
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: basement_entrance_and_hall
      event: 2001
  action:
    - service: deconz.configure
      data:
        entity: light.basement_hall_spots
        field: '/state' # state for deconz light, action for deconz group
        data: {"bri_inc":254, "transitiontime":20}

- alias: Increase Stop Basement Hall
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: basement_entrance_and_hall
      event: 2003
  action:
    - service: deconz.configure
      data:
        entity: light.basement_hall_spots
        field: "/state"
        data: {"bri_inc":0}

- alias: Decrease Start Basement Hall
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: basement_entrance_and_hall
      event: 3001
  action:
    - service: deconz.configure
      data:
        entity: light.basement_hall_spots
        field: '/state' # state for deconz light, action for deconz group
        data: {"bri_inc":-254, "transitiontime":20}

- alias: Decrease Stop Basement Hall
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: basement_entrance_and_hall
      event: 3003
  action:
    - service: deconz.configure
      data:
        entity: light.basement_hall_spots
        field: "/state"
        data: {"bri_inc":0}



- alias: Turn On Basement Hall 2
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: basement_hall_switch
      event: 1002
  action:
    service: light.turn_on
    entity_id: light.basement_hall_spots

- alias: Turn Off Basement Hall 2
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: basement_hall_switch
      event: 2002
  action:
    service: light.turn_off
    entity_id: light.basement_hall_spots

- alias: Increase Start Basement Hall 2
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: basement_hall_switch
      event: 1001
  action:
    - service: deconz.configure
      data:
        entity: light.basement_hall_spots
        field: '/state' # state for deconz light, action for deconz group
        data: {"bri_inc":254, "transitiontime":20}

- alias: Increase Stop Basement Hall 2
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: basement_hall_switch
      event: 1003
  action:
    - service: deconz.configure
      data:
        entity: light.basement_hall_spots
        field: "/state"
        data: {"bri_inc":0}

- alias: Decrease Start Basement Hall 2
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: basement_hall_switch
      event: 2001
  action:
    - service: deconz.configure
      data:
        entity: light.basement_hall_spots
        field: '/state' # state for deconz light, action for deconz group
        data: {"bri_inc":-254, "transitiontime":20}

- alias: Decrease Stop Basement Hall 2
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: basement_hall_switch
      event: 2003
  action:
    - service: deconz.configure
      data:
        entity: light.basement_hall_spots
        field: "/state"
        data: {"bri_inc":0}