############ FUGA Switch ############
- alias: Turn On Basement Room
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: basement_room_switch
      event: 1002
  action:
    service: light.turn_on
    entity_id: light.basement_room_spots

- alias: Turn Off Basement Room
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: basement_room_switch
      event: 2002
  action:
    service: light.turn_off
    entity_id: light.basement_room_spots

- alias: Increase Start Basement Room
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: basement_room_switch
      event: 1001
  action:
    - service: deconz.configure
      data:
        entity: light.basement_room_spots
        field: '/state' # state for deconz light, action for deconz group
        data: {"bri_inc":254, "transitiontime":20}

- alias: Increase Stop Basement Room
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: basement_room_switch
      event: 1003
  action:
    - service: deconz.configure
      data:
        entity: light.basement_room_spots
        field: "/state"
        data: {"bri_inc":0}

- alias: Decrease Start Basement Room
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: basement_room_switch
      event: 2001
  action:
    - service: deconz.configure
      data:
        entity: light.basement_room_spots
        field: '/state' # state for deconz light, action for deconz group
        data: {"bri_inc":-254, "transitiontime":20}

- alias: Decrease Stop Basement Room
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: basement_room_switch
      event: 2003
  action:
    - service: deconz.configure
      data:
        entity: light.basement_room_spots
        field: "/state"
        data: {"bri_inc":0}