- alias: Turn On Basement Entrance
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: basement_entrance_and_hall
      event: 4002
  action:
    service: light.turn_on
    entity_id: light.basement_entrance_spots

- alias: Turn Off Basement Entrance
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: basement_entrance_and_hall
      event: 5002
  action:
    service: light.turn_off
    entity_id: light.basement_entrance_spots

- alias: Increase Start Basement Entrance
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: basement_entrance_and_hall
      event: 4001
  action:
    - service: deconz.configure
      data:
        entity: light.basement_entrance_spots
        field: '/state' # state for deconz light, action for deconz group
        data: {"bri_inc":254, "transitiontime":20}

- alias: Increase Stop Basement Entrance
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: basement_entrance_and_hall
      event: 4003
  action:
    - service: deconz.configure
      data:
        entity: light.basement_entrance_spots
        field: "/state"
        data: {"bri_inc":0}

- alias: Decrease Start Basement Entrance
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: basement_entrance_and_hall
      event: 5001
  action:
    - service: deconz.configure
      data:
        entity: light.basement_entrance_spots
        field: '/state' # state for deconz light, action for deconz group
        data: {"bri_inc":-254, "transitiontime":20}

- alias: Decrease Stop Basement Entrance
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: basement_entrance_and_hall
      event: 5003
  action:
    - service: deconz.configure
      data:
        entity: light.basement_entrance_spots
        field: "/state"
        data: {"bri_inc":0}
