- alias: Motion Detected At Front Door Night
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_motion
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    - service: light.turn_on
      data:
        entity_id: light.front_door_spots
        brightness_pct: 50
        transition: 0.3


- alias: Motion Cleared At Front Door
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_motion
      from: 'on'
      to: 'off'
      for: '00:05:00'
  action:
    - service: light.turn_off
      entity_id: light.front_door_spots