blueprint:
  name: Light2 On/Off
  description: Turn a light On or Off with a zigbee switch in DeConz. Use for example a FoH Double switch right side
  domain: automation
  input:
    switch_id:
      name: DeConz Event Switch ID
      selector:
        text:
    light:
      name: Light Entity
      selector:
        entity:
          domain: light

trigger:
  platform: event
  event_type: deconz_event
  event_data: 
    id: !input switch_id
action:
  - service_template: >
      {% if trigger.event.data.event == 3002 %}
        light.turn_on
      {% elif trigger.event.data.event == 4002 %}
        light.turn_off
      {% endif %}
    data:
      entity_id: !input light

