# - platform: template
#   sensors:
#     android_tv_1_volume:
#       friendly_name: "Android TV 1 Volume"
#       value_template: "{{ state_attr('media_player.android_tv_1', 'volume_level')|round(2) }}"

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'date_time_utc'
    - 'date_time_iso'
    - 'time_date'
    - 'time_utc'
    - 'beat'


- platform: template
  sensors: 
    cover_position_livingroom_1:
      friendly_name: "Cover Position Living Room 1"
      value_template: "{{ state_attr('cover.livingroom_blind_1', 'current_position') }}"


# - platform: rest
#   name: Renovation
#   resource: >-
#     https://usage.dk/jaff/?address=J%C3%B8rgen%20Jensens%20Vej%2034&county=naestved&index=
#   value_template: '{{ value_json.address }}'
#   scan_interval: 1800
#   json_attributes:
#     - services
# - platform: template
#   sensors:
#     renovation_storskrald_0:
#       friendly_name: Renovation - Storskrald
#       value_template: >-
#         {% set months = ["Januar",
#         "Februar","Marts","April","Maj","Juni","Juli", "August", "September",
#         "Oktober", "November", "December"] %} {% set date =
#         strptime(states.sensor.renovation.attributes["services"]["storskrald_0"]["next"]["date"],'%Y-%m-%d')
#         %} {% set day =
#         states.sensor.renovation.attributes["services"]["storskrald_0"]["next"]["day"]
#         %} {{ day }} d. {{date.day}}. {{months[date.month - 1]}} ( om {{
#         ((date.timestamp() - now().timestamp()) / (24 * 60 *
#         60))|round(0,'ceil') }} dage )
#       attribute_templates:
#         day: >-
#           {{
#           states.sensor.renovation.attributes["services"]["storskrald_0"]["next"]["day"]
#           }}
#         date: >-
#           {{
#           states.sensor.renovation.attributes["services"]["storskrald_0"]["next"]["date"]
#           }}
#         schedule: >-
#           {{
#           states.sensor.renovation.attributes["services"]["storskrald_0"]["schedule"]
#           }}
#     renovation_metalglasplast_0:
#       friendly_name: Renovation - Metal Glas Plast
#       value_template: >-
#         {% set months = ["Januar",
#         "Februar","Marts","April","Maj","Juni","Juli", "August", "September",
#         "Oktober", "November", "December"] %} {% set date =
#         strptime(states.sensor.renovation.attributes["services"]["metal glas
#         plast_0"]["next"]["date"],'%Y-%m-%d') %} {% set day =
#         states.sensor.renovation.attributes["services"]["metal glas
#         plast_0"]["next"]["day"] %} {{ day }} d. {{date.day}}.
#         {{months[date.month - 1]}} ( om {{ ((date.timestamp() -
#         now().timestamp()) / (24 * 60 * 60))|round(0,'ceil') }} dage )
#       attribute_templates:
#         day: >-
#           {{ states.sensor.renovation.attributes["services"]["metal glas
#           plast_0"]["next"]["day"] }}
#         date: >-
#           {{ states.sensor.renovation.attributes["services"]["metal glas
#           plast_0"]["next"]["date"] }}
#         schedule: >-
#           {{ states.sensor.renovation.attributes["services"]["metal glas
#           plast_0"]["schedule"] }}
#     renovation_madrest_0:
#       friendly_name: Renovation - Mad/rest
#       value_template: >-
#         {% set months = ["Januar",
#         "Februar","Marts","April","Maj","Juni","Juli", "August", "September",
#         "Oktober", "November", "December"] %} {% set date =
#         strptime(states.sensor.renovation.attributes["services"]["mad/rest_0"]["next"]["date"],'%Y-%m-%d')
#         %} {% set day =
#         states.sensor.renovation.attributes["services"]["mad/rest_0"]["next"]["day"]
#         %} {{ day }} d. {{date.day}}. {{months[date.month - 1]}} ( om {{
#         ((date.timestamp() - now().timestamp()) / (24 * 60 *
#         60))|round(0,'ceil') }} dage )
#       attribute_templates:
#         day: >-
#           {{
#           states.sensor.renovation.attributes["services"]["mad/rest_0"]["next"]["day"]
#           }}
#         date: >-
#           {{
#           states.sensor.renovation.attributes["services"]["mad/rest_0"]["next"]["date"]
#           }}
#         schedule: >-
#           {{
#           states.sensor.renovation.attributes["services"]["mad/rest_0"]["schedule"]
#           }}
